# Generated by Django 4.0.3 on 2022-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
