# Generated by Django 4.0.3 on 2022-04-05 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0007_typecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
