# Generated by Django 4.0.3 on 2022-04-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_type_element_typeelement'),
        ('comment_app', '0009_alter_contact_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.element'),
        ),
    ]
