# Generated by Django 4.0.3 on 2022-03-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_element',
            new_name='TypeElement',
        ),
    ]
