# Generated by Django 4.0.3 on 2022-04-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('ini_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name_ga', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_view', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spend', models.FloatField()),
                ('date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.influencer')),
            ],
        ),
        migrations.AddField(
            model_name='influencer',
            name='campaign',
            field=models.ManyToManyField(through='dash_app.InfluencerCampaign', to='dash_app.campaign'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='type_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.typeinfluencer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.ManyToManyField(to='dash_app.country'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.mark'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.medium'),
        ),
    ]
